mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
        username: root
    rabbitmq:
        addresses: 127.0.0.1:5672
        username: guest
        password: guest
